### ISSUE TITLE
Outreachy

### ISSUE THREAD

**Issue by nickvidal** [enarx/outreach#15]
Our recommendation is to have the Enarx project (and the Confidential Computing Consortium) as part of Outreachy program from Software Freedom Conservancy, a diversity initiative that provides paid, remote internships. Past Outreachy interns include: 92% women, 4% transgender, genderqueer, or non-binary people, 64% people of color, and 12% people from a historically disadvantaged caste or tribe.

Outreachy internships provide a stipend of $6,000 USD for full-time commitment that lasts 3 months (running from Dec. 6, 2021 to March 4, 2022).

Ideally, this initiative should be run by the Confidential Computing Consortium, and each project would be responsible for developing their own activities within this program. By promoting this initiative as a Consortium, the Enarx community can grow much faster than if promoting on its own.

Members of the Confidential Computing Consortium will be invited to mentor these interns. Interns can choose to work on any open source project that is part of the Confidential Computing Consortium. As of now, these projects are Enarx, Open Enclave SDK, Keystone, Veracruz, Graphene, Occlum, and Trusted Compute Framework.

We would have to get approval to move forward as a Consortium by September 10, 2021, the deadline to apply to the Outreachy program. Mentors are welcome to submit internship projects by September 17, 2021. If we don’t get an approval from the Consortium, Enarx can decide to run this as part of the Outreachy program on its own.

Prior to the start of the internship, the projects would have to develop one or more proposals of interesting activities that the interns should be able to complete in 3 months.

https://www.outreachy.org/

**Comment by nickvidal** [comment]
Ashley has sent the CCC community application to the Outreachy program:

https://www.outreachy.org/communities/cfp/confidential-computing-consortium/

An Enarx project proposal has also been sent to Outreachy. We'll be asking interns to create one or more demos on top of Enarx and build tutorials. Something very simple that will not require them understanding the actual internals of Enarx, and something they can complete in 3 months.

**Comment by nickvidal** [comment]
The following CCC projects are participating in the Outreachy program: Enarx, Gramine, and Occlum.

**Comment by nickvidal** [comment]
The Outreachy internship starts today. Ajay, Jennifer, and Shraddha are joining us:

https://blog.enarx.dev/welcome-outreachy-interns/

**Comment by pranayrauni** [comment]
Hi, my Outreachy 2022 intial application is approved. I want to contribute to Enarx. From where should I start?
