### ISSUE TITLE
Improve LinkedIn page banner

### ISSUE THREAD

**Issue by axelsimon** [enarx/outreach#3]
A first temporary banner was put, but following @m-dombrowski we want to improve.

I changed it to a very simple one in black and white with an Enarx logo, but we may want something cooler / more complex.
We can track this here.

**Comment by m-dombrowski** [comment]
Are we interested in retaining the revised black and white banner currently on the LinkedIn page or something more inline with LinkedIn culture expectations?

**Comment by axelsimon** [comment]
I think i'm not very _au fait_ of what LinkedIn expectations are regarding that sort of stuff. Could you elaborate a bit?

**Comment by axelsimon** [comment]
Reached out to LF graphics team to see if they could help, as discussed during the last outreach meeting.
