### ISSUE TITLE
Consider Linux Foundation CII badging

### ISSUE THREAD

**Issue by MikeCamel** [enarx/outreach#35]
https://www.coreinfrastructure.org/

This is not without contention, but it aims to show that a project meets particular processes and best practices around security.

**Comment by nickvidal** [comment]
Initial OpenSSF Best Practices:

https://bestpractices.coreinfrastructure.org/en/projects/5414

It was presented as part of the Enarx Project Review from the CCC:

https://github.com/confidential-computing/governance/blob/main/TAC/Meetings/2022/2022-03-10/Enarx%20Review%202022%20Slides.pdf
