### ISSUE TITLE
Improve SGX-Measurement page

### ISSUE THREAD

**Issue by npmccallum** [enarx/outreach#39]
The page needs a short prose introduction explaining the purpose of the page. It also needs a link to the SGX pdf. Likewise, each table needs a section and/or page reference for easy primary source lookup.

**Comment by Immy-delish** [comment]
Hello @npmccallum, I am an outreachy applicant, i would like to work on this issue. Please let me know if I can move on with this.

> The page needs a short prose introduction explaining the purpose of the page. It also needs a link to the SGX pdf. Likewise, each table needs a section and/or page reference for easy primary source lookup.
