### ISSUE TITLE
LinkedIn updates: interviews with the Enarx team

### ISSUE THREAD

**Issue by axelsimon** [enarx/outreach#4]
@m-dombrowski suggested we start a series of short (written) interviews with various members of the Enarx community that we could post to LinkedIn.

This issue is to track this overall effort. We should probably create one issue per interviewee.

**Comment by m-dombrowski** [comment]
Just to confirm, @axelsimon  will be the first team member to interview?

**Comment by axelsimon** [comment]
it's looking that way, @m-dombrowski. I (finally) sent you my answers, we can discuss here some more or over direct chat.

**Comment by axelsimon** [comment]
Just a quick update to remind ourselves to start getting the first one out there.

**Comment by m-dombrowski** [comment]
> Just a quick update to remind ourselves to start getting the first one out there.

I've got it ready for the 11/17/2020 Outreach team meeting.

**Comment by m-dombrowski** [comment]
First draft created as issue #12
