### ISSUE TITLE
OC3 - 2022-02-17

### ISSUE THREAD

**Issue by nickvidal** [enarx/outreach#42]
**Info**
- Open Confidential Computing Conference 2022
- https://www.oc3.dev/

**Dates**
- CFP opens:     2021-11-03
- CFP closes:    2021-12-07
- CFP results:   2021-12-20

**Location**
Online (On site - Germany)

**CFP**
https://www.papercall.io/oc3-2022

**Comment by nickvidal** [comment]
Talked with Daniela about presenting a Demo of Enarx.

**Comment by MikeCamel** [comment]
Note - @MikeCamel is on the committee for this.

**Comment by nickvidal** [comment]
### From zero to hero: making Confidential Computing accessible

How can we make Confidential Computing accessible, so that developers from all levels can quickly learn and use this technology? In this session, we welcome three Outreachy interns, who had zero knowledge of Confidential Computing, to demonstrate what they've developed in just a few months.

**Description**

Implementing state-of-the-art Confidential Computing is complex, right? Developers must understand how Trusted Execution Environments work (whether they are process-based or VM-based), be familiar with the different platforms that support Confidential Computing (such as Intel's SGX or AMD's SEV), and have knowledge of complex concepts such as encryption and attestation.

Enarx, an open source project part of the Confidential Computing Consortium, abstracts all these complexities and makes is really easy for developers from all levels to implement and deploy applications to Trusted Execution Environments.

The Enarx project partnered with Outreachy, a diversity initiative from the Software Freedom Conservancy, to welcome three interns, who had zero knowledge of Confidential Computing. During just a few of months, they learned the basics and started building demos in their favorite language, from simple to more complex.

In this session, they'll have to the opportunity to showcase their demos and share what they've learned. Our hope is to demonstrate that Confidential Computing can be made accessible and easy to use by all developers.

**Notes**

The goals of this proposal is to highlight the importance of making Confidential Computing accessible and to demonstrate that this is very much possible. Much more than just featuring one particular open source project, this proposals offers an opportunity for all involved in Confidential Computing to be inspired and to seek ways to make this technology as accessible as possible. We also put the Confidential Computing Consortium's internship program in the spotlight, and provide opportunities for these interns to showcase their work.

**Comment by nickvidal** [comment]
These 2 sessions were accepted:
- Understanding trust relationships for Confidential Computing - Mike
- From zero to hero: making Confidential Computing accessible - Nick

**Comment by nickvidal** [comment]
Videos are up on YouTube:

**Understanding trust relationships for Confidential Computing - Mike**
https://www.youtube.com/watch?v=pLIAFCLNre4

**From zero to hero: making Confidential Computing accessible - Nick**
https://www.youtube.com/watch?v=9GEZ1pnGN0I
