### ISSUE TITLE
SCALE 19x - 2022-03-03

### ISSUE THREAD

**Issue by nickvidal** [enarx/outreach#45]
**Info:**
- SCALE 19x
- Dates: 2022-03-03 - 2022-03-06
- Location: Pasadena, CA
- https://www.socallinuxexpo.org/scale/19x

**CFP:**
- 2021-11-30: deadline for proposal
- Security track: Covering all topics in realm of open source security. These include Security research, innovative security designs, cool tools, topical issues, "How to's" to cost effective open source security solutions and everything in-between.

**Comment by MikeCamel** [comment]
"WebAssembly as a consistent platform for Confidential Computing" accepted (Mike & Nathaniel)
