### ISSUE TITLE
Academia Collaboration

### ISSUE THREAD

**Issue by nickvidal** [enarx/outreach#47]
We are looking to engage with research groups (either in academia, non-profits, or companies) doing research on Confidential Computing and adjacent areas. Our goal is to increase the number of published papers and/or dissertations that make reference to the Enarx project, as well as be part of relevant academic conferences.

**Comment by nickvidal** [comment]
Initial list of universities we want to collaborate with:
- Tampere University
- KU Leuven
- University of Texas at Dallas
- University of Waterloo
- Federal University of Parana

**Comment by MikeCamel** [comment]
I'd also suggest:

- [Aarhus University](https://international.au.dk/)
- [Royal Holloway](https://www.royalholloway.ac.uk/)
