### ISSUE TITLE
FOSDEM - 2023-02-04 - 2023-02-05

### ISSUE THREAD

**Issue by fidencio** [enarx/outreach#49]
**Info**
- FOSDEM - Confidential Computing devroom
- Dates: 2023-02-04 - 2023-02-05
- Location: Brussels, Belgium (2023-02-05, with an online possibility on 2023-02-04)
- www.fosdem.org/2023
- Any other relevant information

**Dates**
- CFP closes:    2022-12-02
- CFP results:   2022-12-07

**Location**
ULB Solbosch Campus, Brussels, Belgium

**CFP**
URL to the Call for Proposals / Papers: https://falder.org/fosdem23-cfp

**Comment by nickvidal** [comment]
Thank you @fidencio! We'll be submitting a talk!
