### ISSUE TITLE
FOSDEM 2024 Confidential Computing Devroom - Feb 4, 2024

### ISSUE THREAD

**Issue by jovanbulck** [enarx/outreach#52]
Not sure how active Enarx is at the moment, but dropping this here anyway. It may be interesting for the community to have an update on the current state and future of the project!

**Info**

https://falder.org/fosdem24-cfp

**Dates**
- CFP closes:    2024-12-01

**Location**
Brussels, Belgium

**CFP**
URL to the Call for Proposals / Papers: https://falder.org/fosdem24-cfp
-

**Comment by rjzak** [comment]
This looks fantastic, tagging @nickvidal; I probably cannot travel.
