### ISSUE TITLE
LinkedIn Enarx page "About/Overview" section

### ISSUE THREAD

**Issue by m-dombrowski** [enarx/outreach#6]
Who is our target audience on LinkedIn? Once we define the audience, we can develop the outreach approach and feel for this channel. Recruitment? Industry connections? Project awareness?

The Wiki has "about" sections that target specific audiences. Do we want to transplant one of these sections into the LinkedIn "About" section once the audience has been identified.

Thoughts?

edit: platform clarification

**Comment by axelsimon** [comment]
I would argue the target audience is twofold:
- people who follow IT (technologists, developers, CIOs) but don't know about confidential computing or haven't thought about the problem Enarx aims to solve
- people who are into security (security boffins, as the Register would say) and already know about TEEs, and have some understanding of confidential computing even if the terms is not one they know or use.

@MikeCamel @shaunix what do you think?

**Comment by m-dombrowski** [comment]
@axelsimon 
Would it be appropriate to copy and paste the Wiki introduction? We don't necessarily need to reinvent introductory information for LinkedIn.

https://github.com/enarx/enarx/wiki/Enarx-Introduction
